/*
 * @(#)URLServiceName.java		1.0 06/06/2013
 */

package ar.com.agea.hub.rol.utils;

/**
 * Representa los nombres de los servicios GWP, HUB y PASE.
 * <p>
 * Estos nombres son utilizados por la clase URLServiceResolver y HttpHeadersResolver
 * para resolver las rutas de los servicios GWP, HUB y PASE. 
 * 
 * @author		Eduardo Barrera
 * @version		1.0 06/06/2013
 */
public enum URLServiceName {

	// Servicios de GWP.
	GWP_REALIZAR,
	
	// Servicios de HUB.
	// Servicios de Aviso.
	HUB_EXECUTE_NOTIFICAR_PAGO,
	HUB_GET_CONFIGURACIONES_ORDENAMIENTO_PANTALLA,
	HUB_GET_ITEMS_ORDENAMIENTO_AVISO,
	HUB_GET_ITEMS_ORDENAMIENTO_AVISO_GROUP,
	HUB_GET_ORDENES_PUBLICACION_BY_CAPTURADOR,
	HUB_UPDATE_ESTADO_AVISO,
	HUB_UPDATE_ORDEN_PUBLICACION,
	HUB_SAVE_ORDEN_PUBLICACION,
	HUB_GET_TEMPLATE_PRECARGA,
	HUB_GET_ORDEN_PUBLICACION_BY_ID,
	
	// Servicios de Common.
	HUB_GET_CARACTERES_INVALIDOS_JUSTIFICACION,
	HUB_GET_PROPIEDADES_DEFAULT,
	HUB_GET_PAISES,
	HUB_GET_PROVINCIAS,
	HUB_GET_LOCALIDADES,
	
	// Servicios de Facturación.
	HUB_VALIDATE_ORDEN_FACTURADA_EN_SAP,
	
	// Servicios de Interfaz Dinámica.
	HUB_GET_BIENES,
	HUB_GET_FAMILIAS,
	HUB_GET_FAMILIAS_BY_FILTER,
	HUB_GET_FAMILIA_BY_CLASE_AVISO,
	HUB_GET_CLASE_BY_CODIGO,
	HUB_GET_PERMISO_ATRIBUTO_BY_FILTER,
	
	// Servicios de Pretasador.
	HUB_EXECUTE_TASAR,
	
	// Servicios de Producto.
	HUB_EXECUTE_JUSTIFICAR,
	HUB_GET_CALENDARIO,
	HUB_GET_NIVELES_ESTRUCTURA,
	HUB_GET_PRODUCTO_COMERCIAL,
	HUB_GET_PRODUCTO_COMERCIAL_DEFAULT,
	HUB_GET_PRODUCTOS,
	HUB_GET_TIPOS_OPERACION,
	HUB_GET_ZONAS_COMERCIALIZACION,
	HUB_VALIDATE_PALABRAS_PROHIBIDAS,
	HUB_GET_TEMPLATES_DETALLADO,
	HUB_GET_IMAGENES,
	HUB_GET_CONFIGURACIONES_PROMOCION_PANTALLA,
	HUB_VALIDATE_PROMOCIONES,
	HUB_VALIDATE_VIGENCIA,
	
	// Servicios de Usuario Cliente.
	HUB_GET_CAPTURADOR,
	HUB_GET_TARJETAS_PAGO,
	
	HUB_SAVE_CAPTURADOR,
	HUB_UPDATE_CAPTURADOR,
	HUB_UPDATE_SEXO_FECHA_CAPTURADOR
	
}
